server:
  port: 8088

spring:
  application:
    name: cg-lms-config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
