server:
  port: ${SEVER_PORT}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  config:
    import: configserver:${CONFIG_SERVER_URL}
  datasource:
    driver-class-name: ${DRIVER_CLASS_NAME}
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: ${DEFAULT_ZONE}