server:
  port: 8085

spring:
  application:
    name: cg-lms-payment-service
  config:
    import: configserver:${CONFIG_SERVICE_URL:http://localhost:8088/}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/payment_service
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
